apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
  labels:
    type: frontend
spec:
  containers:
  - name: configmap-pod
    image: service1:v1
    ports:
      - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128M"
        cpu: "500m"
    envFrom:
      - configMapRef:
          name: s1-config-01