apiVersion: apps/v1
kind: Deployment
metadata:
  name: s1-deployment
  labels:
    type: frontend

spec:
  replicas: 10

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 4
      maxUnavailable: 0

  selector:
    matchLabels:
      type: frontend

  template:
    metadata:
      labels:
        type: frontend
    
    spec:
      containers:
        - name: service1
          image: service1:v1
          ports:
            - containerPort: 80