\c dts;

INSERT INTO question (original_content,img)
VALUES 
    ('What should you do before making a U-turn?',null),
    ('What should you do as you approach this bridge?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/2.Q.png'),
    ('Where should you avoid overtaking?',null),
    ('What does this curved arrow road marking mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/4.Q.png'),
    ('What should you do if your mobile phone rings while you''re driving or riding?',null),
    ('Why are these yellow lines painted across the road?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/6.Q.png'),
    ('What should you do when you''re approaching traffic lights that have been green for some time?',null),
    ('What should you do before slowing down or stopping your vehicle?',null),
    ('You''re following a large vehicle. Why should you stay a safe distance behind it?',null),
    ('Why should you use your mirrors when you see a hazard ahead?',null),
    ('You''re waiting to turn right at the end of a road. What should you do if your view is obstructed by parked vehicles?',null),
    ('There are objects hanging from your interior mirror. Why could this be a hazard?',null),
    ('You''re on a long motorway journey. What should you do if you start to feel sleepy?',null),
    ('Why should you switch your headlights on when it first starts to get dark?',null),
    ('What''s most likely to distract you while you''re driving?',null),
    ('You''re driving your car. When may you use a hand-held mobile phone?',null),
    ('You''re driving on a wet road. What should you do if you have to stop your vehicle in an emergency',null),
    ('What should you do when you move off from behind a parked car?',null),
    ('You''re travelling along this road. How should you pass the cyclist?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/19.Q.png'),
    ('When do windscreen pillars cause a serious obstrucion to your view?',null),
    ('What should you do if you can''t see clearly behind when you''re reversing?',null),
    ('What does the term ''blind spot'' mean?',null),
    ('What''s likely to happen if you use a hands-free phone while you''re driving',null),
    ('You''re turning right onto a dual carriageway. What should you do before emerging?',null),
    ('You''re wwaiting to emerge from a junction. The windscreen pillar is restricting your view. What should you be particularly aware of?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/25.Q.png'),
    ('How can you make sure that a satellite navigation (satnav)',' system doesn''t distract you when you''re driving?,null'),
    ('What must you do when the amber light is flashing at a pelican crossing?',null),
    ('Why should you never wave people across at pedestrian crossings?',null),
    ('Why is it dangerous to drive too close to the vehicle ahead?',null),
    ('What will happen if you follow this vehicle too closely?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/30.Q.png'),
    ('What''s the minimum time gap you should leave when following a vehicle on a wet road?',null),
    ('You''re being overtaken by a long, heavily laden lorry. What should you do if it''s taking a long time for it to overtake?',null),
    ('Which vehicle will use a blue flashing beacon?',null),
    ('What should you do if you''re being followed by an ambulance showing flashing blue light?',null),
    ('What type of emergency vehicle is fitted with a green flashing beacon?',null),
    ('Who should obey diamond-shaped traffic signs?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/36.Q.png'),
    ('On a road where trams operate, which vehicles will be most at risk from the tram rails?',null),
    ('When should you use your vehicle''s horn?',null),
    ('You''re in a one-way street and want to turn right. Where should you position your vehicle when there are two lanes?',null),
    ('You wish to turn right ahead. Why should you take up the correct position in good time?',null),
    ('Which type of crossing allows cyclists to ride across while pedestrians are also crossing?',null),
    ('You''re travelling at the legal speed limit. What should you do if the vehicle behind approaches quickly, flashing its headlights?',null),
    ('When should you flash your headlights at other road users?',null),
    ('You''re approaching an unmarked crossroads. How should you deal with the junction?',null),
    ('The conditions are good and dry. When should you use the ''two-second rule''?',null),
    ('Which colour follows the green signal at a puffin crossing?',null),
    ('You''re in a line of traffic. What action should you take if the driver behind is following very closely?',null),
    ('You''re driving on a clear night. Which lights should you use if the national speed limit applies and there''s a steady stream of oncoming traffic?',null),
    ('You''re driving behind a large goods vehicle. What should you do if it signals left but steers to the right?',null),
    ('You''re driving along this road. What should you do if the red car cuts in close in front of you?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/50.Q.png'),
    ('You''re waiting in a traffic queue at night. How can you avoid dazzling drivers behind you?',null),
    ('You''re driving in traffic at the speed limit for the road. What should you do if the driver behind is trying to overtake?',null),
    ('What does it mean if the signs at a bus lane show no times of operation?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/53.Q.png'),
    ('What should you do when a person herding sheep asks you to stop?',null),
    ('What should you do when you''re overtaking a horse and rider?',null),
    ('You''re approaching a zebra crossing. WHat should you do if pedestrians are waiting to cross?',null),
    ('What should you do if a vehicle pulls out in front of you at a junction?',null),
    ('You''re approaching a red light at a puffin crossing. Pedestrians are on the crossing. When will the red light change?',null),
    ('Which instrument-panel warning light would show that headlights are on main beam?',null),
    ('When should you leave a two-second gap between your vehicle and the one in front?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/60.Q.png'),
    ('You''re driving at night on an unlit road. What should you do if you''re following another vehicle?',null),
    ('What should you do if you''re driving a slow-moving vehicle on a narrow winding road?',null),
    ('You''re driving a car that has a diesel engine. What can a loose filler cap on your fuel tank cause?',null),
    ('What should you do to avoid fuel spillage?',null),
    ('What style of driving causes increased risk to everyone?',null),
    ('How would under-inflated tyres affect your vehicle?',null),
    ('When are you not allowed to sound your vehicle''s horn?',null),
    ('What makes the vehicle in the picture ''environmentally friendly''?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/68.Q.png'),
    ('Why have ''red routes'' been introduced in major cities?',null),
    ('What''s the purpose of road humps, chicanes and narrowings?',null),
    ('What''s the purpose of a catalytic converter?',null),
    ('When should tyre pressures be checked?',null),
    ('When will your vehicle use more fuel?',null),
    ('How should you dispose of a used vehicle battery?',null),
    ('What''s most likely to increase fuel consumption?',null),
    ('The fluid level in your battery is low. What fluid should you use to top it up?',null),
    ('You''re parked on the road at night. When must you use parking lights?',null),
    ('How can you reduce the environmental harm caused by your motor vehicle?',null),
    ('What can cause excessive or uneven tyre wear?',null),
    ('You need to top up your battery with distilled water. What level should you fill it to?',null),
    ('How can you plan your route before starting a long journey?',null),
    ('Why is it a good idea to plan your journey to avoid busy times?',null),
    ('How will your journey be affected by travelling outside the busy times of day?',null),
    ('You plan your route before starting a journey. Why should you also plan an alternative route?',null),
    ('You have to arrive on time for an appointment. How shoud you plan for the journey?',null),
    ('What can you expect if you drive using rapid acceleration and heavy braking?',null),
    ('What could cause you to crash if the level is allowed to get too low?',null),
    ('What should you do if your anti-lock brakes (ABS)'','' warning light stays on?',null),
    ('What does it mean if this light comes on while you''re driving?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/89.Q.png'),
    ('Why is it important to wear suitable shoes when you''re driving?',null),
    ('If you''re involved in a collision, what will reduce the risk of neck injury?',null),
    ('What does it mean if your vehicle keeps bouncing after you sharply press down and release on the bodywork over a wheel?',null),
    ('How will a roof rack affect your car?',null),
    ('What makes your tyres illegal?',null),
    ('What''s the legal minimum depth of tread for car tyres?',null),
    ('You''re carrying two 13-year-old children and their parents in your car. Who''s responsible for seeing that the children wear seat belts?',null),
    ('How can drivers help the environment?',null),
    ('How can you avoid wasting fuel?',null),
    ('What could you do to reduce the volume of traffic on the roads?',null),
    ('What''s most likely to waste fuel?',null),
    ('What part of the car does the law require you to keep in good condition?',null),
    ('How much more fuel will you use by driving at 70 mph, compared with driving at 50 mph?',null),
    ('What should you do if your vehicle pulls to one side when you use the brakes?',null),
    ('What will happen if your car''s wheels are unbalanced?',null),
    ('What can be damaged if you turn the steering wheel when the car isn''t moving?',null),
    ('What''s the safest thing to do if you have to leave valuables in your car?',null),
    ('What may help to deter a thief from stealing your car?',null),
    ('What should you remove from your car before leaving it unattended?',null),
    ('What should you do when leaving your vehicle parked and unattended?',null),
    ('What will reduce fuel consumption?',null),
    ('Your service your own vehicle. How should you dipose of the old engine oil?',null),
    ('Why do MOT tests include an exhaust emission test?',null),
    ('How can you reduce the damage your vehicle causes to the environment?',null),
    ('How will you benefit from following the manufacturer''s service schedule for your vehicle?',null),
    ('How should you drive when you''re driving along a road that has road humps?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/115.Q.png'),
    ('When should you check the engine oil level?',null),
    ('You''re having difficulty finding a parking space in a busy town. Can you park on the zigzag lines of a zebra crossing?',null),
    ('What should you do when you leave your car unattended for a few minutes?',null),
    ('Why should you try and park in a secure car park?',null),
    ('Where would parking your vehicle cause an obstruction?',null),
    ('What''s the most important reason for having a properly adjusted head restraint?',null),
    ('What can you do to reduce environmental damage caused by your vehicle?',null),
    ('What can people who live or work in towns and cities do to help reduce urban pollution levels?',null),
    ('How can you reduce the chances of your car being broken into when leaving it unattended?',null),
    ('How can you help to prevent your car radio being stolen?',null),
    ('How can you reduce the risk of your vehicle being broken into at night?',null),
    ('What will help you to keep your car secure?',null),
    ('On a vehicle, where would you find a catalytic converter?',null),
    ('What can you achieve if you drive smoothly?',null),
    ('Which driving technique can help you save fuel?',null),
    ('How can driving in a fuel-efficient manner help protect the environment?',null),
    ('What does fuel-efficient driving achieve?',null),
    ('What''s the legal minimum tread depth for tyres on your trailer or caravan?',null),
    ('When is fuel consumption at its highest?',null),
    ('When may a passsenger travel in a car without wearing a sear belt?',null),
    ('You''re driving a friend''s children home from school. They''re both under 14 years old. Who''s responsible for making sure they wear a seat belt or approved child restraint where required?',null),
    ('What''s likely to happen if you put too much oil in your engine?',null),
    ('You have to make an unexpected journey. You''re carrying a five-year-old child on the back seat of your car. They''re under 1.35 metres (4 feet 5 inches), tall. How should you seat them if a correct child restraint isn''t available?',null),
    ('You''re carrying an 11-year-old child on the front seat of your car. They''re under 1.35 metres (4 feet 5 inches), tall. What seat belt security must be in place?',null),
    ('You''re stopped at the side of the road. What must you do if you''ll be waiting there for some time?',null),
    ('You want to put a rear-facing baby seat on the front passenger seat. What must you do if the passenger seat is protected by a frontal airbag?',null),
    ('You''re leaving your vehicle parked on a road and unattended. When may you leave the engine running?',null),
    ('What does it mean if the Electronic Stability Control (ESC), indicator lamp lights up while you''re driving?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/143.Q.png'),
    ('How much can stopping distances increase in icy conditions?',null),
    ('What requires extra care when you''re driving or riding in windy conditions?',null),
    ('Why should you keep well to the left as you approach a right-hand bend?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/146.Q.png'),
    ('You''ve just gone through flood water. What should you do to make sure your brakes are working properly?',null),
    ('What will be affected if the road surface becomes soft in very hot weather?',null),
    ('Where is your vehicle most likely to be affected by side winds?',null),
    ('You''re following a vehicle on a wet road. You stay a safe distance behind it. What should you do if a driver overtakes you and pulls into the gap you''ve left?',null),
    ('You''re travelling on the motorway. How can you lower the risk of a collision when the vehicle behind is following too closely?',null),
    ('You''re following other vehicles in fog. You have your headlights on dipped beam. What else can you do to reduce the chances of being in a collision?',null),
    ('What should you do when you''re using a contraflow system?',null),
    ('How can you avoid wheelspin when you''re driving on an icy road?',null),
    ('What''s the main cause of skidding?',null),
    ('You''re driving in freezing conditions. What should you do as you approach a sharp bend?',null),
    ('You''re about to start a journey in freezing weather. What part of your vehicle should you clear of ice and snow?',null),
    ('What will help you to move off on a snowy surface?',null),
    ('What should you do when you''re driving in snowy conditions?',null),
    ('What''s the main benefit of driving a four-wheel-drive vehicle?',null),
    ('You''re about to go down a steep hill. What should you do to control the speed of your vehicle?',null),
    ('What should you do when you park a car facing downhill?',null),
    ('You''re driving in a built-up area that has traffic-calming measures. What should you do when you approach a road hump?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/163.Q.png'),
    ('On what type of road surface may anti-lock brakes be ineffective?',null),
    ('You''re driving a vehicle that has anti-lock brakes. How should you apply the footbrake when you need to stop in an emergency?',null),
    ('You''re driving along a country road. You see this sign. What should you do after dealing safely with the hazard?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/166.Q.png'),
    ('What would suggest you''re driving on an icy road?',null),
    ('You''re driving along a wet road. How can you tell if your vehicle''s tyres are losing their grip on the surface?',null),
    ('In which conditions will your overall stopping distance increase?',null),
    ('You''re driving on an open road in dry weather. What distance should you keep from the vehicle in front?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/170.Q.png'),
    ('How can you use your vehicle''s engine as a brake?',null),
    ('How should you use anti-lock brakes when you need to stop in an emergency?',null),
    ('What lights should you use when you''re driving on a wet motorway and vehicles are throwing up surface spray?',null),
    ('What can result when you travel for long distances in neutral (known as coasting)?',null),
    ('What should you do before starting a journey in foggy weather?',null),
    ('What should you do when you''re overtaking a motorcyclist on a windy day?',null),
    ('Where would you expect to see these markers?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/177.Q.png'),
    ('What''s the main hazard shown in this picture?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/178.Q.png'),
    ('Which road user has caused a hazard?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/179.Q.png'),
    ('What should the driver of the car approaching the crossing do?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/180.Q.png'),
    ('What should the driver of the grey car be especially aware of?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/181.Q.png'),
    ('What should you expect if you see this sign ahead?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/182.Q.png'),
    ('What should you do as you approach this cyclist?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/183.Q.png'),
    ('Why must you take great care when emerging from this junction?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/184.Q.png'),
    ('Which type of vehicle should you be ready to give way to as you approach this bridge?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/185.Q.png'),
    ('What type of vehicle could you expect to meet in the middle of the road?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/186.Q.png'),
    ('What must you do at this junction?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/187.Q.png'),
    ('What should you do if a driver pulls out of a side road in front of you, causing you to brake hard?',null),
    ('How would age affect an older person''s driving ability?',null),
    ('Do you need to plan rest stops when you''re planning a long journey?',null),
    ('What should you do if the red lights start flashing as you approach a level crossing?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/191.Q.png'),
    ('You''re approaching a crossroads. What should you do if the traffic lights have failed?',null),
    ('What should the driver of the red car (arrowed) do?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/193.Q.png'),
    ('You''re following a slower-moving vehicle. What should you do if there''s a junction just ahead on the right?',null),
    ('What should you do as you approach this overhead bridge?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/195.Q.png'),
    ('Why are vehicle mirrors often slightly curved (convex)','?,null'),
    ('You''re on a three-lane motorway. How should you overtake a slow-moving lorry in the middle lane if it''s showing this sign?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/197.Q.png'),
    ('What should you do if you think the driver of the vehicle in front has forgotten to cancel their right indicator?',null),
    ('What''s the main hazard the driver of the red car (arrowed), should be aware of?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/199.Q.png'),
    ('What type of vehicle displays this yellow sign?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/200.Q.png'),
    ('What hazard should you be aware of when travelling along this street?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/201.Q.png'),
    ('What''s the main hazard you should be aware of when following this cyclist?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/202.Q.png'),
    ('A driver''s behaviour has upset you. How can you get over this incident safely?',null),
    ('How should you drive in areas with traffic-calming measures?',null),
    ('Why should you slow down as you approach this hazard?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/205.Q.png'),
    ('Why are place names painted on the road surface?',null),
    ('Some two-way roads are divided into three lanes. Why are they particularly dangerous?',null),
    ('What type of vehicle uses an amber flashing beacon on a dual carriageway?',null),
    ('What does this signal from a police officer mean to oncoming traffic?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/209.Q.png'),
    ('Why should you be cautious when going past this bus waiting at a bus stop?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/210.Q.png'),
    ('Where would it be unsafe to overtake?',null),
    ('How can drinking alcohol affect your ability to drive?',null),
    ('What does the solid white line at the side of the road indicate?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/213.Q.png'),
    ('You''re driving towards this level crossing. What would be the first warning of an approaching train?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/214.Q.png'),
    ('You''re behind this cyclist. When the traffic lights change, what should you do?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/215.Q.png'),
    ('You intend to turn left at the traffic lights. What should you do just before turning?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/216.Q.png'),
    ('Why should you reduce your speed here?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/217.Q.png'),
    ('What might you expect to happen in this situation?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/218.Q.png'),
    ('You''re driving on a road with several lanes. What do these signs above the lanes mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/219.Q.png'),
    ('You''re invited to a pub lunch. What should you do if you know that you''ll have to drive in the evening?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/220.Q.png'),
    ('What will become more expensive after you''ve been convicted of driving while unfit through drink or drugs?',null),
    ('What advice should you give to a driver who has had a few alcoholic drinks at a party?',null),
    ('What should you do about driving if you''ve been taking medicine that causes drowsiness?',null),
    ('What should you do if a doctor prescribes drugs that are likely to affect your driving?',null),
    ('What must you do if your ability to drive is impaired during a period of illness?',null),
    ('What should you do if you begin to feel drowsy while you''re driving?',null),
    ('What should you do if you become tired while you''re driving on a motorway?',null),
    ('You''re about to drive home. What should you do if you feel very tired and have a severe headache?',null),
    ('What can you do to help prevent tiredness on a long journey?',null),
    ('You take some cough medicine given to you by a friend. What should you do before driving your car?',null),
    ('You''re driving on a one-way street. What should you do if you realise you''ve taken the wrong route?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/231.Q.png'),
    ('What will be a serious distraction while you''re driving?',null),
    ('What should you do if the vehicle starts reversing off the driveway?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/233.Q.png'),
    ('You''ve been involved in an argument that''s made you feel angry. What should you do before starting your journey?',null),
    ('You''re driving on this dual carriageway. Why may you need to slow down?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/235.Q.png'),
    ('You''ve just been overtaken by this motorcyclist. What should you do if the rider cuts in sharply?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/236.Q.png'),
    ('You''re about to drive your car. What should you do if you can''t find the glasses you need to wear?',null),
    ('How does drinking alcohol affect your driving behaviour?',null),
    ('Why should you check the information leaflet before taking any medicine?',null),
    ('You need glasses to read a vehicle number plate at the required distance. When must you wear them?',null),
    ('Which type of glasses would make driving at night more difficult?',null),
    ('What can seriously reduce your ability to concentrate?',null),
    ('What must you do if your eyesight has become very poor and you''re no longer able to meet the driver''s eyesight requirements?',null),
    ('When should you use hazard warning lights?',null),
    ('You want to turn left at this junction. What should you do if your view of the main road is restricted?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/245.Q.png'),
    ('You''re driving a car ftted with automatic transmission. When would you use ''kick down''?',null),
    ('What should you do if it''s raining and you''re following this lorry on a motorway?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/247.Q.png'),
    ('You''re driving towards this left-hand bend. What danger should you be anticipating?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/248.Q.png'),
    ('What should you do if the traffic in the left-hand lane is slowing?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/249.Q.png'),
    ('When may you use hazard warning lights?',null),
    ('You''re waiting to emerge at a junction. Your view is restricted by parked vehicles. What can help you to see traffic on the road you''re joining?',null),
    ('What must you do if poor health affects your driving?',null),
    ('Why should the junction on the left be kept clear?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/253.Q.png'),
    ('What should you do if you start to feel drowsy while you''re driving on a motorway?',null),
    ('Which sign means that there may be people walking along the road?',null),
    ('What should you do if you want to turn left at a junction where pedestrians have started to cross?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/256.Q.png'),
    ('What hazard should you be especially aware of if you''re turning left into a side road?',null),
    ('Why should you check for motorcyclists just before turning right into a side road?',null),
    ('Why is a toucan crossing different from other crossings?',null),
    ('How will a school crossing patrol signal you to stop?',null),
    ('Where would you see this sign?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/261.Q.png'),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/262.Q.png'),
    ('You see a pedestrian carrying a white stick that also has a red band. What does this mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/263.Q.png'),
    ('What should you do if you see older people crossing the road ahead?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/264.Q.png'),
    ('What should you do when you see an older person about to cross the road ahead?',null),
    ('You''re approaching a roundabout. What should you do if a cyclist ahead is signalling to turn right?',null),
    ('Which vehicle should you allow extra room as you overtake them?',null),
    ('Why should you look carefully for motorcyclists and cyclists at junctions?',null),
    ('You''re waiting to come out of a side road. Why should you look carefully for motorcycles?',null),
    ('Why do motorcyclists use dipped headlights in daylight?',null),
    ('Why do motorcyclists wear bright clothing?',null),
    ('Why do motorcyclists often look round over their right shoulder just before turning right?',null),
    ('Which is the most vulnerable road user?',null),
    ('You''re approaching a roundabout. What should you do if there are horses being ridden in front of you?',null),
    ('As you approach a pelican crossing, the lights change to green. What should you do if older people are still crossing?',null),
    ('What action should you take when you see flashing amber lights under a school warning sign?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/276.Q.png'),
    ('Why should these road markings be kept clear?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/277.Q.png'),
    ('Where would you see this sign?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/278.Q.png'),
    ('You''re following two cyclists as they approach a roundabout in the left-hand lane. Where would you expect the cyclists to go?',null),
    ('You''re travelling behind a moped. What should you do if you want to turn left a short distance ahead?',null),
    ('You see a horse rider as you approach a roundabout. What should you do if they''re signalling right but keeping well to the left?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/281.Q.png'),
    ('How should you react to inexperienced drivers?',null),
    ('What should you do when you''re following a learner driver who stalls at a junction?',null),
    ('You''re on a country road that has no pavement. What should you anticipate finding on your side of the road?',null),
    ('You''re following a cyclist. What should you do when you wish to turn left a short distance ahead?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/285.Q.png'),
    ('A horse rider is in the left-hand lane approaching a roundabout. Where should you expect the rider to go?',null),
    ('Powered vehicles used by disabled people are small and can be hard to see. What must they display if they''re travelling on a dual carriageway?',null),
    ('What does it mean when a moving vehicle is showing a flashing amber beacon?',null),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/289.Q.png'),
    ('What should you do when you see these horse riders in front?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/290.Q.png'),
    ('What''s the purpose of these road markings?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/291.Q.png'),
    ('What should you do if the left-hand pavement is closed due to street repairs?',null),
    ('What should you do when you''re following a motorcyclist along a road that has a poor surface?',null),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/294.Q.png'),
    ('You''re approaching this roundabout. What should you do when a cyclist is keeping to the left while signalling to turn right?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/295.Q.png'),
    ('What should you do when you''re approaching this crossing?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/296.Q.png'),
    ('What does it mean if you see a pedestrian with a dog that has a yellow or burgundy coat?',null),
    ('Who may use toucan crossing?',null),
    ('This junction, controlled by traffic lights, has a marked area between two stop lines. What''s this for?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/299.Q.png'),
    ('You''re about to overtake a cyclist. Why should you leave them as much room as you would give to a car?',null),
    ('What should you do when you''re passing loose sheep on the road?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/301.Q.png'),
    ('At night, what does it mean if you see a pedestrian wearing reflective clothing and carrying a bright red light?',null),
    ('You''ve just passed your driving test. How can you reduce your risk of being involved in a collision?',null),
    ('You want to reverse into a side road. What should you do if you aren''t sure that the area behind your car is clear?',null),
    ('You''re about to reverse into a side road. What should you do if a pedestrian is waiting to cross behind your car?',null),
    ('Which road users are most difficult to see when you''re reversing your car?',null),
    ('You want to turn right from a junction. What should you do if your view is restricted by parked vehicles?',null),
    ('You''re at the front of a queue of traffic waiting to turn right into a side road. Why is it important to check your right mirror just before turning?',null),
    ('You''ve driven up to a pelican crossing. What must you do while the amber light is flashing?',null),
    ('You''ve stopped at a pelican crossing. What should you do if a disabled person is crossing slowly in front of you and the lights change to green?',null),
    ('You''re driving past a line of parked cars. What should you do if a ball bounces out into the road ahead?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/311.Q.png'),
    ('You want to turn right from a main road into a side road. What should you do just before turning?',null),
    ('You''re driving in a slow-moving queue of traffic. What should you do just before changing lane?',null),
    ('You''re driving in town. Why should you be careful if there''s a bus at a bus stop on the other side of the road?',null),
    ('How should you overtake horse riders?',null),
    ('Why should you allow extra room while overtaking a motorcyclist on a windy day?',null),
    ('Where should you take particular care to look for motorcyclists and cyclists?',null),
    ('The road outside this school is marked with yellow zigzag lines. What do these lines mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/318.Q.png'),
    ('You''re driving past parked cars. What should you do if you see a bicycle wheel sticking out between the cars?',null),
    ('You''re driving at night. What should you do if you''re dazzled by a vehicle behind you?',null),
    ('You''re driving towards a zebra crossing. What should you do if a person in a wheelchair is waiting to cross?',null),
    ('You''re turning right from a main road into a side road. There''s no oncoming traffic. What should you do if pedestrians are standing on the pavement waiting to cross the side road?',null),
    ('You''re travelling on a narrow section of road. What should you do if a horse rider ahead is riding in the centre of the lane?',null),
    ('You''re about to overtake a cyclist on a road that has a 30 mph speed limit. How much room should you leave them as you overtake?',null),
    ('You''re turning left from amain road into a side road. What should you do if there''s a pedestrian on the pavement waiting to cross the side road?',null),
    ('You''re about to overtake a slow-moving motorcyclist. Which sign would make you take sppecial care?',null),
    ('You''re waiting to turn right out of a minor road. It''s clear to the left but a lorry is coming from the right. Why should you wait, even if you have enough time to turn?',null),
    ('You''re following a long vehicle as it approaches a crossroads. What should you do if it signals left but moves out to the right?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/328.Q.png'),
    ('You''re following love vehicle approaching a crossroads. What should you do if the driver signals right but moves close to the left-hand kerb?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/329.Q.png'),
    ('You''re approaching a mini-roundabout. What should you do if a long vehicle in front signals left but positions over to the right?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/330.Q.png'),
    ('You''re driving on a single carriageway road. Why should you keep well back while you''re following a large vehicle?',null),
    ('You''re travelling behind a bus. What should you do if it pulls up at a bus stop?',null),
    ('You''re following a lorry on a wet road. What should you do when spray makes it difficult to see the road ahead?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/333.Q.png'),
    ('You''re leaving a safe gap as you follow a large vehicle. What should you do if a car moves into this gap?',null),
    ('What should you do when you''re approaching a bus that''s signalling to move away from a bus stop?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/335.Q.png'),
    ('What should you do if you want to overtake a long, slow-moving vehicle on a busy road?',null),
    ('Which vehicles are least likely to be affected by side wind?',null),
    ('What should you do as you approach this lorry?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/338.Q.png'),
    ('You''re following a large vehicle as it approaches a crossroads. What should you do if the driver signals to turn left?',null),
    ('Why is it more difficult to overtake a large vehicle than a car?',null),
    ('It''s very windy. What should you do if you''re behind a motocyclist who''s overtaking a high-sided vehicle?',null),
    ('What should you do if there''s a bus at a bus stop ahead of you?',null),
    ('What should you be prepared to do in this situation?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/343.Q.png'),
    ('Why should drivers be more careful on roads where trams also operate?',null),
    ('You''re towing a caravan. Which is the safest type of rear-view mirror to use?',null),
    ('You''re driving in heavy traffic on a wet road. Which lights should you use if there''s a lot of surface spray?',null),
    ('What should you do if you overtake a cyclist when it''s very windy?',null),
    ('When may you overtake another vehicle on their left?',null),
    ('You''re travelling in very heavy rain. How is this likely to affect your overall stopping distance?',null),
    ('What should you do when you''re overtaking at night?',null),
    ('When may you wait in a box junction?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/351.Q.png'),
    ('Which plate may appear with this road sign?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/352.Q.png'),
    ('What''s the reason for traffic-calming measures?',null),
    ('What colour are the reflective studs along the left-hand edge of the motorway?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/354.Q.png'),
    ('What''s a rumble device designed to do?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/355.Q.png'),
    ('What should you do if you have to make a journey in foggy conditions?',null),
    ('What must you do when you''re overtaking a car at night?',null),
    ('You''re travelling on a road that has road humps. What should you do when the driver in front I travelling more slowly than you?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/358.Q.png'),
    ('What''s the purpose of the yellow lines painted across the road?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/359.Q.png'),
    ('What should you do when you meet an oncoming vehicle on a single-track road?',null),
    ('The road is wet. Why would a motorcyclist steer around drain covers while they were cornering?',null),
    ('Why should you test your brakes after this hazard?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/362.Q.png'),
    ('Why should you reduce your speed when you''re driving or riding in fog?',null),
    ('What will happen to your car when you drive up steep hill?',null),
    ('You''re driving on the motorway in windy conditions. What should you do as you overtake a high-sided vehicle?',null),
    ('You''re driving in fog. Why should you keep well back from the vehicle in front?',null),
    ('What should you do if you park in the road when it''s foggy?',null),
    ('You''re driving at night. What should you do if you''re dazzled by headlights coming towards you?',null),
    ('When may front fog lights be used?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/369.Q.png'),
    ('You''re driving with your front fog lights switched on. What should you do if the fog has cleared?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/370.Q.png'),
    ('Why should you switch off your rear fog lights when the fog has cleared?',null),
    ('What will happen if you use rear fog lights in good conditions?',null),
    ('Why would you fit chains to your wheels?',null),
    ('How can you use your vehicle''s engine to control your speed?',null),
    ('Why could it be dangerous to keep the clutch down, or select neutral, for long periods of time while you''re driving?',null),
    ('You''re driving on an icy road. What distance from the car in front should you drive?',null),
    ('Which lights must you use if you''re driving on a well-lit motorway at night?',null),
    ('You''re driving on a motorway at night. Which lights should you have on if there are other vehicles just ahead of you?',null),
    ('What will affect your vehicle''s stopping distance?',null),
    ('When will you feel the effects of engine braking?',null),
    ('Which lights should you switch on when daytime visibility is poor but not seriously reduced?',null),
    ('Why are vehicles fitted with rear fog lights?',null),
    ('There''s been a heavy fall of snow. What should you consider before driving in these conditions?',null),
    ('What should you check before you start a journey in foggy weather?',null),
    ('You''ve been driving in fog. What must you do when the visibility improves?',null),
    ('Why is it dangerous to leave rear fog lights switched on after the fog has cleared?',null),
    ('What will happen if you hold the clutch pedal down or roll in neutral for too long?',null),
    ('Why is it bad technique to coast when you''re driving downhill?',null),
    ('What should you do when dealing with this hazard?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/389.Q.png'),
    ('Why is travelling in neutral for long distances (known as coasting), bad driving technique?',null),
    ('When must you use dipped headlights during the day?',null),
    ('You''re joining a motorway from a slip road. How should you deal with traffic already on the motorway?',null),
    ('What''s the national speed limit on motorways for cars and motorcycles?',null),
    ('Which vehicles should use the left-hand lane on a three-lane motorway?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/394.Q.png'),
    ('Which vehicles aren''t allowed to use the right-hand lane of a three-lane motorway?',null),
    ('Your vehicle breaks down on a motorway and you need to call for help. Why might it be better to use an emergency roadside telephone rather than a mobile phone?',null),
    ('Your vehicle broke down on the hard shoulder of a motorway, but has now been repaired. How should you rejoin the main carriageway?',null),
    ('You''re travelling along a motorway. Where would you find a crawler or climbing lane?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/398.Q.png'),
    ('What do these motorway signs mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/399.Q.png'),
    ('Where are amber reflective studs found on a motorway?',null),
    ('What colour are the reflective studs between the lanes on a motorway?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/401.Q.png'),
    ('What colour are the reflective studs between a motorway and a slip road?',null),
    ('Your vehicle has broken down on a motorway. In which direction should you walk to find the nearest emergency telephone?',null),
    ('Why is it important to make full use of the slip road as you join a motorway?',null),
    ('How should you position yourself when you use the emergency telephone on a motorway?',null),
    ('What colour are the reflective studs between the hard shoulder and the left-hane lane of a motorway?',null),
    ('On a three-lane motorway, which lane shoulde you use if there''s no traffic ahead?',null),
    ('What should you do when going through a contraflow system on a motorway?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/408.Q.png'),
    ('You''re on a three-lane motorway. Which lane are you in if there are red reflective studs on your left and white ones to your right?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/409.Q.png'),
    ('What should you do when you''re approaching roadwork on a motorway?',null),
    ('Which vehicle are prohibited from using the motorway?',null),
    ('What should you do while you''re driving or riding alone a motorway?',null),
    ('What should you do immediately after joining a motorway?',null),
    ('When would you use the right-hand lane on a three-lane motorway?',null),
    ('You''re on a motorway that isn''t subject to smart motorway regulations. When should you use the hard shoulder?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/415.Q.png'),
    ('You''re in the right-hand lane of a three-lane motorway. What do these overhead signs mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/416.Q.png'),
    ('When are you allowed to stop on a motorway?',null),
    ('You''re travelling in the left-hand lane of a three-lane motorway. How should you react to traffic joining from a slip road?',null),
    ('How should you use the lanes on a motorway?',null),
    ('You''re travelling along a motorway. When are you allowed to overtake on the left?',null),
    ('When would you use an emergency refuge area on a smart motorway?',null),
    ('Traffic officers operate on motorways and some primary routes in England and Wales. What are they authorised to do?',null),
    ('You''re on a smart motorway. What does it mean when a red cross is displayed above the hard shoulder?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/423.Q.png'),
    ('You have stopped in an emergency refuge area. What must yo do before you rejoin the carriageway?',null),
    ('How should you rejoin the motorway after a breakdown on the hard shoulder?',null),
    ('You''re on a smart motorway. What does it mean when a mandatory speed limit is displayed above the hard shoulder?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/426.Q.png'),
    ('How do smart motorways prevent traffic bunching?',null),
    ('What helps to reduce traffic bunching on a motorway?',null),
    ('When may you stop on a motorway?',null),
    ('What''s the national speed limit for a car or motorcycle on a motorway?',null),
    ('You stop on the hard shoulder of a motorway and use the emergency telephong. Where''s the best place to wait for help to arrive?',null),
    ('You''re on a motorway. What must you do if there''s a red cross showing above every lane?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/432.Q.png'),
    ('You''re on a smart motorway. What does it mean if a red cross is showing above the hard shoulder and mandatory speed limits above all other lanes?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/433.Q.png'),
    ('On a smart motorway, what does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/434.Q.png'),
    ('Where should you stop to rest if you feel tired while you''re travelling along a motorway?',null),
    ('What''s the speed limit for a car towing a trailer on a motorway?',null),
    ('When should you use the left-hand lane of a motorway?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/437.Q.png'),
    ('You''re driving on a motorway and have to slow down suddenly due to a hazard ahead. How can you warn drivers behind of the hazard?',null),
    ('Your car gets a puncture while you''re driving on the motorway. What should you do when you''ve stopped on the hard shoulder?',null),
    ('What should you do if you''re driving on a motorway and you miss the exit that you wanted to take?',null),
    ('Your vehicle has broken down on a motorway. What should you do if you aren''t able to get onto the hard shoulder?',null),
    ('Why is it particularly important to check your vehicle before making a long motorway journey?',null),
    ('You''re driving on a motorway. What does it mean if the car in front shows its hazard warning lights for a short time?',null),
    ('You''re driving on the motorway. Which lane should you get into well before you reach your exit?',null),
    ('What restrictions apply to people who have a provisional driving licence?',null),
    ('Your vehicle breaks down on a motorway and you manage to stop on the hard shoulder. What should you do if you use your mobile phone to call for help?',null),
    ('You''re towing a trailer along a three-lane motorway. When may you use the right-hand lane?',null),
    ('What would you expect to find at a contraflow system on a motorway?',null),
    ('What''s the meaning of this sign?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/449.Q.png'),
    ('What''s the national speed limit for cars and motorcycles on a dual carriageway?',null),
    ('There are no speed-limit signs on the road. How is a 30 mph limit generally indicated?',null),
    ('What will the speed limit usually be where you can see street lights but no speed-limit signs?',null),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/453.Q.png'),
    ('What should you do if you want to overtake a tractor but aren''t sure that it''s safe?',null),
    ('Which vehicle is most likely to take an unusual course at a roundabout?',null),
    ('When may you stop on a clearway?',null),
    ('What''s the meaning of this sign?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/457.Q.png'),
    ('You''re looking for somewhere to park at night. When may you park on the right-hand side of the road?',null),
    ('When should you use the right-hand lane of a three-lane dual carriageway?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/459.Q.png'),
    ('You''re approaching a busy junction. What should you do when, at the last moment, you realise you''re in the wrong lane?',null),
    ('Where may you overtake on a one-way street?',null),
    ('What signal should you give when you''re going straight ahead at a roundabout?',null),
    ('Which vehicle might have to take a different course from normal at a roundabout?',null),
    ('When may you enter a box junction?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/464.Q.png'),
    ('When may you stop and wait in a box junction?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/465.Q.png'),
    ('Who is authorised to signal you to stop?',null),
    ('What should you do if you see a pedestrian waiting at a zebra crossing?',null),
    ('Which road users benefit from toucan crossing?',null),
    ('You''re waiting at a pelican crossing. What does it mean when the red light changes to flashing amber?',null),
    ('You see these double white lines along the centre of the road. When may you park on the left','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/470.Q.png'),
    ('You’re turning right at a crossroads. An oncoming driver is also turning right. What''s the advantage of turning behind the oncoming vehicle?',null),
    ('You''re travelling along a residential street. There are parked vehicles on the left-hand side. Why should you keep your speed down?',null),
    ('What should you do when there''s an obstruction on your side of the road?',null),
    ('When would you use the right-hand lane of a two-lane dual carriageway?',null),
    ('Who has priority at an unmarked crossroad?',null),
    ('What''s the nearest you may park to a junction?',null),
    ('You’re looking for somewhere to safely park your vehicle. Where would you choose to park?',null),
    ('You''re waiting at a level crossing. What must you do if a train passes but the lights keep flashing?',null),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/479.Q.png'),
    ('What must you do if you come across roadworks that have a temporary speed limit displayed?',null),
    ('You''re in a built-up area at night and the road is well lit. Why should you use dipped headlights?',null),
    ('You''re turning right from a main road into a side road. There''s no oncoming traffic. What should you do if pedestrians are standing on the pavement waiting to cross the side road?',null),
    ('What''s the national speed limit on a single carriageway road for cars and motorcycles?',null),
    ('What should you do when you park at night on a road that has a 40 mph speed limit?',null),
    ('Where will you see these red and white markers?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/485.Q.png'),
    ('You''re travelling on a motorway in England. When must you stop your vehicle?',null),
    ('How should you signal if you''re going straight ahead at a roundabout?',null),
    ('When may you frive over a pavement?',null),
    ('A single carriageway road has this sign. What''s the maximum permitted speed for a car towing a trailer?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/489.Q.png'),
    ('What’s the speed limit for a car towing a caravan on a dual carriageway?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/490.Q.png'),
    ('You want to park and you see this sign. What should you do on the days and times shown?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/491.Q.png'),
    ('A cycle lane, marked by a solid white line, is in operation. What does this mean for car drivers?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/492.Q.png'),
    ('You''re going to turn left from a main road into a minor road. What should you do as you approach the junction?',null),
    ('You''re waiting at a level crossing. What should you do if the red warning lights continue to flash after a train has passed by?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/494.Q.png'),
    ('What should you do if the amber lights come on and a warning sounds while you''re driving over a level crossing?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/495.Q.png'),
    ('You''re driving on a busy main road. What should you do if you find that you''re driving in the wrong direction?',null),
    ('When may you drive without wearing your seat belt?',null),
    ('How far are you allowed to reverse?',null),
    ('What should you do when you''re unsure whether it''s safe to reverse your vehicle?',null),
    ('Why could it be dangerous to reverse from a side road into a main road?',null),
    ('You want to turn right at a box junction. What should you do if there''s oncoming traffic?',null),
    ('You''re reversing into a side road. When would your vehicle be the greatest hazard to passing traffic?',null),
    ('Where''s the safetest place to park your vehicle at night?',null),
    ('When may you stop on an urban clearway?',null),
    ('You''re looking for somewhere to park your vehicle. What should you do if the only free spaces are marked for disabled drivers?',null),
    ('You''re on a road that''s only wide enough for one vehicle. What should you do if a car is coming towards you?',null),
    ('You''re driving at night with your headlights on main beam. A vehicle is overtaking you. When should you dip your headlights?',null),
    ('When may you drive a car in this bus lane?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/508.Q.png'),
    ('Other than direction indicators, how can you give signals to other road users?',null),
    ('You''re parked in a busy high street. What''s the safest way yo trun your vehicle around so you can drive in the opposite direction?',null),
    ('Where should you park your vehicle at night?',null),
    ('You''re driving in the right-hand lane of a dual carriageway. What should you do if you see a sign showing that the right-hand lane is closed 800 yards ahead?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/512.Q.png'),
    ('You''re driving on a road that has a cycle lane. What does it mean if the lane is marked by a broken white line?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/513.Q.png'),
    ('When are you allowed to park in a parking bay for disabled drivers?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/514.Q.png'),
    ('When mus you stop your vehicle?',null),
    ('How can you identify traffic signs that give orders?',null),
    ('What shape are traffic signs giving orders?',null),
    ('Which type of sign tells you what you must not do?',null),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/519.Q.png'),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/520.Q.png'),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/521.Q.png'),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/522.Q.png'),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/523.Q.png'),
    ('Which sign means ''no entry''?',null),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/525.Q.png'),
    ('Which type of vehicle does this sign apply to?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/526.Q.png'),
    ('Which sign means no motor vehicles allowed?',null),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/528.Q.png'),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/529.Q.png'),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/530.Q.png'),
    ('Which sign means ''no stopping''?',null),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/532.Q.png'),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/533.Q.png'),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/534.Q.png'),
    ('What does this traffic sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/535.Q.png'),
    ('What''s the meaning of this traffic sign?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/536.Q.png'),
    ('What shape is a ''stop'' sign?',null),
    ('In winter, road signs can become covered by snow. What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/538.Q.png'),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/539.Q.png'),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/540.Q.png'),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/541.Q.png'),
    ('What messages are given by circular traffic signs that have a blue background?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/542.Q.png'),
    ('Where would you see a contraflow bus lane?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/543.Q.png'),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/544.Q.png'),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/545.Q.png'),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/546.Q.png'),
    ('What''s the purpose of triangular shaped signs?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/547.Q.png'),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/548.Q.png'),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/549.Q.png'),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/550.Q.png'),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/551.Q.png'),
    ('What information would be shown in a triangular road sign?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/552.Q.png'),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/553.Q.png'),
    ('Which sign means that pedestrians may be walking along the road?',null),
    ('Which sign means there''s a double bend ahead?',null),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/556.Q.png'),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/557.Q.png'),
    ('Which sign means the end of a dual carriageway?',null),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/559.Q.png'),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/560.Q.png'),
    ('What does this traffic sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/561.Q.png'),
    ('You''re about to overtake. What should you do when you see this sign?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/562.Q.png'),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/563.Q.png'),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/564.Q.png'),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/565.Q.png'),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/566.Q.png'),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/567.Q.png'),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/568.Q.png'),
    ('Which is the sign for a ring road?',null),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/570.Q.png'),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/571.Q.png'),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/572.Q.png'),
    ('What does a red traffic light mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/573.Q.png'),
    ('At traffic lights, what does it mean when the amber light shows on its own?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/574.Q.png'),
    ('You''re a junction controlled by traffic lights. When should you wait at a green light?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/575.Q.png'),
    ('You''re in the left-hand lane at traffic lights, waiting to turn left. Which signal means you must wait?',null),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/577.Q.png'),
    ('Who has priority when traffic lights are out of order?',null),
    ('Where would you find thses flashing red light signals?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/579.Q.png'),
    ('What do these zigzag white lines mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/580.Q.png'),
    ('When may you cross a double solid white line in the middle of the road?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/581.Q.png'),
    ('What does this road marking mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/582.Q.png'),
    ('Where would you see this road marking?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/583.Q.png'),
    ('Which diagram shows a hazard warning line?',null),
    ('Why does this junction have a ''stop'' sign and a stop line on the road?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/585.Q.png'),
    ('What does this line across the road at the entrance to a roundabout mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/586.Q.png'),
    ('How will a police officer in a patrol vehicle signal for you to stop?',null),
    ('You''re approaching a junction where the traffic lights aren''t working. What should you do when a police officer gives this signal?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/588.Q.png'),
    ('What does this arm signal mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/589.Q.png'),
    ('What does this motorway sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/590.Q.png'),
    ('What does this motorway sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/591.Q.png'),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/592.Q.png'),
    ('What does ''25'' mean on this motorway sign?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/593.Q.png'),
    ('How should the right-hand lane of a three-lane motorway be used?',null),
    ('Where can you find reflective amber studs on a motorway?',null),
    ('Where would you find green reflective studs on a motorway?',null),
    ('What should you do when you see this sign as you travel along a motorway?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/597.Q.png'),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/598.Q.png'),
    ('Which sign means that the national speed limit applies?',null),
    ('What''s the national speed limit on a single carriageway road?',null),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/601.Q.png'),
    ('What does this sign indicate?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/602.Q.png'),
    ('What does this traffic sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/603.Q.png'),
    ('What should you do when you see this sign at a crossroads?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/604.Q.png'),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/605.Q.png'),
    ('You''re on a motorway. A lorry has stopped in the right-hand lane. What should you do when you see this sign on the lorry?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/606.Q.png'),
    ('You''re on a motorway. What should you do if there''s a red cross showing on the signs above your lane only?',null),
    ('When may you sound your vehicle''s horn?',null),
    ('Your vehicle is stationary. When may you use its horn?',null),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/610.Q.png'),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/611.Q.png'),
    ('Which sign means you have priority over oncoming vehicles?',null),
    ('What do the long white lines along the contre of the road mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/613.Q.png'),
    ('What''s the reason for the hatched area along the centre of this road?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/614.Q.png'),
    ('Other drivers may sometimes flash their headlights at you. What''s the official meaning of this signal?',null),
    ('What does this signal mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/616.Q.png'),
    ('Where would you find these road markings?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/617.Q.png'),
    ('A police car if following you. What should you do if the police officer flashes the headlights and points to the left?',null),
    ('You see this amber traffic light ahead. Which light, or lights, will come on next?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/619.Q.png'),
    ('What does it mean if you see this signal on the motorway?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/620.Q.png'),
    ('What must you do when you see this sign?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/621.Q.png'),
    ('Which shape is used for a ''give way'' sign?',null),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/623.Q.png'),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/624.Q.png'),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/625.Q.png'),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/626.Q.png'),
    ('Which sign informs you that you''re coming to a ''no through road''?',null),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/628.Q.png'),
    ('What should you do when you''re approaching traffic lights that have red and amber showing together?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/629.Q.png'),
    ('You''ve stopped at a railway level crossing. What should you do if the red lights continue to flash after a train has gone by?',null),
    ('You''re in a tunnel and you see this sign. What does it mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/631.Q.png'),
    ('Which sign shows that you''re entering a one-way system?',null),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/633.Q.png'),
    ('Which of these signs warns you of a zebra crossing?',null),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/635.Q.png'),
    ('Which sign means there will be two-way traffic crossing your route ahead?',null),
    ('Which arm signal tells you that the car you''re following is going to pull up?',null),
    ('Which sign means turn left ahead?',null),
    ('What should you be aware of if you''ve just passed this sign?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/639.Q.png'),
    ('You''re approaching traffic lights and the red light is showing. What signal will show next?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/640.Q.png'),
    ('What does this sign mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/641.Q.png'),
    ('What does the white line along the side of the road indicate?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/642.Q.png'),
    ('What does this white arrow on the road mean?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/643.Q.png'),
    ('How should you give an arms signal to turn left?',null),
    ('You''ve waiting at a T-junction. What should you do if a vehicle is coming from the right, with its left indicator flashing?','https://dts-resources.s3.ap-southeast-1.amazonaws.com/question-images/645.Q.png'),
    ('When may you use hazard warning lights while you''re driving?',null),
    ('Why should you make sure that your indicators are cancelled after turning at a junction?',null),
    ('You''re driving in busy traffic. You want to pull up just after a junction on the left. When should you signal?',null),
    ('For how long is an MOT certificate normally valid?',null),
    ('What''s a cover note?',null),
    ('You''ve just passed your first practical driving test. What will you have to do if you get six penallty points on your licence in the next two years?',null),
    ('For how long is a Statutory Off-Road Notification (SORN), valid?',null),
    ('What''s a Statutory Off-Road Notification (SORN)?',null),
    ('What''s the maximum fine for driving or riding without insurance?',null),
    ('Who''s legally responsible for ensuring that a vehicle registration cartificate (V5C) is updated?',null),
    ('Your insurer will issue you with an insurance certificate. When must you produce this document for inspection?',null),
    ('When must your vehicle have valid insurance cover?',null),
    ('What do you need before you can legally use a motor vehicle on the road?',null),
    ('What must you have when you apply to renew your vehicle tax?',null),
    ('A police officer asks to see your documents. You don''t have them with you. How many days do you have to produce them at a police station?',null),
    ('When should you update your vehicle registration certificate?',null),
    ('What must you check before you drive someone else''s vehicle?',null),
    ('Your car needs to pass an MOT test. What may be invalidated if you drive the car without a current MOT certificate?',null),
    ('What legal requirement must be met by a newly qualified driver?',null),
    ('What''s covered by third-party insurance?',null),
    ('Who''s responsible for paying the vehicle tax?',null),
    ('What information is found on a vehicle registraation document?',null),
    ('When must you contact the Driver and Vehicle Licensing Agancy (DVLA)?',null),
    ('What circumstances require you to notify the Driver and Vehicle Licensing Agancy (DVLA)?',null),
    ('When could the cost of your insurance be reduced?',null),
    ('In order to supervise a learner driver you need to have held a full driving licence for the same category of vehicle, for at least three years. What other requirement must you meet?',null),
    ('Your care require an MOT certificate. When is it legal to drive it without an MOT certificate?',null),
    ('When will a new car need its first MOT test?',null),
    ('What does third-party insurance cover?',null),
    ('What''s the legal minimum insurance cover you must have to drive on public roads?',null),
    ('What does it mean if your insurance policy has an excess of £500?',null),
    ('When are you allowed to use hazard warning lights?',null),
    ('What should you do if you have to stop while you''re going through a congested tunnel?',null),
    ('You arrive at the scene of a crash where someone is bleeding heavily from a wound in their arm. Nothing is embedded in the wound. What could you do to help?',null),
    ('You''re at an incident. What could you do to help an unconscious casualty?',null),
    ('A casualty isn''t breathing normally and needs CPR. At what rate should you press down and release on the centre of their chest?',null),
    ('Following a collision, a person has been injured. What would be a warning sign for shock?',null),
    ('An injured person has been placed in the recovery position. They''re unconscious but breathing normally. What else should be done?',null),
    ('An injured motorcyclist is lying unconscious in the road. The traffic has stopped and there''s no further danger. What could you do to help?',null),
    ('What should you do if you see a large box fall from a lorry onto the motorway?',null),
    ('You''re going through a long tunnel. What will warn you of congestion or an incident ahead?',null),
    ('11. An adult casualty isn''t breathing. To maintain circulation, CPR should be given. What''s the correct depth to press down on their chest?',null),
    ('You''re the first person to arrive at an incident where people are badly injured. You''ve switched on your hazard warning lights and checked all engines are stopped. What else should you do?',null),
    ('You arrive at the scene of a motorcycle crash. The rider is injured. When should their helmet be removed?',null),
    ('You arrive at an incident. There''s no danger from fire or further collisions and the emergency services have been called. What''s your first priority when attending to an unconscious motorcyclist?',null),
    ('At an incident, someone is unconscious and you want to help. What would be the first thing to check?',null),
    ('What could you do to help injured people at an incident?',null),
    ('There''s been a collision. How can you help a driver who''s suffering from shock?',null),
    ('You arrive at the scene of a motorcycle crash. No other vehicle is involved. The rider is unconscious and lying in the middle of the road. What''s the first thing you should do at the scene?',null),
    ('At an incident, how could you help a small child who isn''t breathing?',null),
    ('At an incident, a casualty isn''t breathing. What should you do while helping them to start breathing again?',null),
    ('At an incident, someone is suffering from severe burns. How could you help them?',null),
    ('You arrive at an incident. A pedestrian is bleeding heavily from a leg wound. The leg isn''t broken and there''s nothing in the wound. How could you help?',null),
    ('At an incident, a casualty is unconscious but breathing. When should you move them?',null),
    ('At an incident, it''s important to look after any casualties. What should you do with them when the area is safe?',null),
    ('Which sign shows that a tanker is carrying dangerous goods?',null),
    ('Which document may the police ask you to produce after you''ve been involved in a collision?',null),
    ('After a collision, someone is unconscious in their vehicle. When should you call the emergency services?',null),
    ('A collision has just happened. An injured person is lying in a busy road. What''s the first thing you should do?',null),
    ('At an incident, how could you help a casualty who has stopped breathing?',null),
    ('You''re at the scene of an incident. How could you help someone who''s suffering from shock?',null),
    ('There''s been a collision. A motorcyclist is lying injured and unconscious. Why should you only remove their helmet if it''s essential?',null),
    ('You''re on a motorway. When can you use hazard warning lights?',null),
    ('You''ve broken down on a two-way road. You have a warning triangle. At least how far from your vehicle should you place the warning triangle?',null),
    ('Your car breaks down on a level crossing. What''s the first thing you should do?',null),
    ('What should you do if a tyre bursts while you''re driving?',null),
    ('What should you do if your vehicle has a puncture on a motorway?',null),
    ('Your vehicle has stalled in the middle of a level crossing. What should you do if the warning bells start to ring while you''re trying to restart the engine?',null),
    ('What should you do before driving into a tunnel?',null),
    ('Which lights should you use when you''re driving in a tunnel?',null),
    ('What should you do to reduce the risk of your vehicle catching fire?',null),
    ('You''re driving on the motorway. What should you do if luggage falls from your vehicle?',null),
    ('What should you do if an instrument panel warning light comes on while you''re driving?',null),
    ('What should you do if your vehicle breaks down in a tunnel?',null),
    ('What should you do if your vehicle catches fire while you''re driving through a tunnel?',null),
    ('What should you do first if your vehicle has broken down on an automatic railway level crossing?',null),
    ('What''s the first thing you must do if you have a collision while you''re driving your car?',null),
    ('What information should you share if you''re involved in a collision that causes damage to another vehicle?',null),
    ('You lose control of your car and damage a garden wall. What must you do if the property owner isn''t available?',null),
    ('What restrictions apply if you''re towing a trailer on a three-lane motorway?',null),
    ('What should you do if you''re towing a trailer and it starts to swing from side to side?',null),
    ('When would you increase the pressure in your tyres so that it''s above the normal value?',null),
    ('How will a heavy load on your roof rack affect your vehicle''s handling?',null),
    ('What would be affected if you carry a very heavy load on your vehicle?',null),
    ('Who''s responsible for making sure that a vehicle isn''t overloaded?',null),
    ('You''re planning to tow a caravan. What will help the handling of the combination?',null),
    ('Are passengers allowed to ride in a caravan that''s being towed?',null),
    ('What safety device must be fitted to a trailer braking system?',null),
    ('You wish to tow a trailer. Where would you find the maximum noseweight for your vehicle''s tow hitch?',null),
    ('How should a load be carried on your roof rack?',null),
    ('You''re carrying a child under three years old in your car. Which restraint is suitable for a child of this age?',null);
